---
match_system_arguments: {'architecture': 'Architecture', 'credential': 'Credential', 'firmware': 'Firmware', 'host': 'Host', 'kernel_command_line': 'KernelCommandLine', 'kernel_version': 'KernelVersion', 'virtualization': 'Virtualization'}

netdev_arguments: {'mac_address': 'MACAddress', 'mtu_bytes': 'MTUBytes'}

wireguard_arguments: {'private_key': 'PrivateKey', 'private_key_file': 'PrivateKeyFile', 'listen_port': 'ListenPort', 'firewall_mark': 'FirewallMark', 'route_table': 'RouteTable', 'route_metric': 'RouteMetric'}

wireguard_peer_arguments: {'public_key': 'PublicKey', 'preshared_key': 'PresharedKey', 'preshared_key_file': 'PresharedKeyFile', 'allowed_ips': 'AllowedIPs', 'endpoint': 'Endpoint', 'persistent_keepalive': 'PersistentKeepalive', 'route_table': 'RouteTable', 'route_metric': 'RouteMetric'}
